apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.deployment.container.name }} 
  ports:
  - protocol: TCP
    port: {{ .Values.service.ports.servicePort }}
    targetPort: {{ .Values.service.ports.targetPort }}
  type: {{ .Values.service.type }}